### ISSUE TITLE
After updating, weather goes all wonky

### ISSUE THREAD

**Issue by Intecpsp** [MichMich/MagicMirror#181] opened 2016-04-16 15:14 UTC
After my weather updates I see this at the top:

![screen shot 2016-04-16 at 11 17 10 am](https://cloud.githubusercontent.com/assets/1164012/14581842/f2dacecc-03c4-11e6-878f-63a86d87e807.png)

The Weather Forecast looks like it is ignoring CSS (overlapping the calendar) and the header containing the wind and sunset somehow gains random text. Just moved to v2 today (reformatted SD card).

**Comment by roxasvalor** [comment] 2016-04-16 16:46
+1 I am having this problem as well.

**Comment by MichMich** [comment] 2016-04-16 16:48
Can you check which module generates the random string (by disabling all others.) and resubmit a screenshot? Thanks!

**Comment by roxasvalor** [comment] 2016-04-16 17:02
I tried disabling all but the current weather module and it doesn't seem to be the cause. I'm adding in other modules now until I find the problem one.

The weird thing is that the error shows up between the sunset image and the sunset time.

**Comment by Intecpsp** [comment] 2016-04-16 17:21
Leaving it a bit longer looks like this:

![screen shot 2016-04-16 at 1 20 27 pm](https://cloud.githubusercontent.com/assets/1164012/14582538/04a4d1a0-03d6-11e6-8fe9-fcbf8a112429.png)

I'll try turning everything else off and letting it sit a bit now.

**Comment by roxasvalor** [comment] 2016-04-16 17:36
I've narrowed it down to running the clock module and the current_weather modules at the same time.

![screenshot](https://cloud.githubusercontent.com/assets/18503539/14582607/c35891e2-03cf-11e6-8d75-c1755474c299.png)

Don't read too deep into the wind speed and direction.

**Comment by Intecpsp** [comment] 2016-04-16 17:40
I actually found it with just the 2 weather modules

![screen shot 2016-04-16 at 1 39 07 pm](https://cloud.githubusercontent.com/assets/1164012/14582630/bbe5a66c-03d8-11e6-9711-b18f595996b4.png)

**Comment by Intecpsp** [comment] 2016-04-16 17:51
Leaving it alone for a bit longer it goes back to normal.

![screen shot 2016-04-16 at 1 51 02 pm](https://cloud.githubusercontent.com/assets/1164012/14582688/51227fb0-03da-11e6-8c64-1564fadd1d63.png)

**Comment by MichMich** [comment] 2016-04-16 17:55
I just pushed an update. Could you give it a try?

**Comment by Intecpsp** [comment] 2016-04-16 17:57
I'm stuck at "Loading weather ... "

**Comment by MichMich** [comment] 2016-04-16 18:01
Sorry, stupid mistake. Please try again.

**Comment by Intecpsp** [comment] 2016-04-16 18:03
Looking good so far, I'll let you know in a few minutes how it goes.

**Comment by Intecpsp** [comment] 2016-04-16 18:05
Just had it again

**Comment by MichMich** [comment] 2016-04-16 18:06
If it happens, could you please check what your mirror received from the open weather api using the web inspector?

**Comment by Intecpsp** [comment] 2016-04-16 18:29
It seems to only happen ON the Raspberry Pi. The left is on my Mac, the right is my Pi on VNC.

![screen shot 2016-04-16 at 2 27 34 pm](https://cloud.githubusercontent.com/assets/1164012/14582892/87ae951e-03df-11e6-8d16-ec07251dd225.png)

**Comment by roxasvalor** [comment] 2016-04-16 18:33
Was just about to update with the same thing.

**Comment by roxasvalor** [comment] 2016-04-16 18:56
Actually, I did a reboot a little while ago and started up the rest of the modules and since then there hasn't been any issue in the top right corner on the Pi. The problem is only on the clock module now.

![screenshot_clock](https://cloud.githubusercontent.com/assets/18503539/14582992/e3a85904-03da-11e6-8940-b74ce75b6ddc.png)

Everything looks good when viewed from Chrome on my Windows computer.

**Comment by Intecpsp** [comment] 2016-04-16 19:05
I just enabled everything again and I concur with roxasvalor. Weather looks okay so far, but the clock is now having that issue.

![screen shot 2016-04-16 at 3 05 17 pm](https://cloud.githubusercontent.com/assets/1164012/14583063/a909e2e0-03e4-11e6-90e0-3a4ac506377e.png)

**Comment by MichMich** [comment] 2016-04-16 19:09
If multiple modules have this issue, it seems like a moment.js issue. Ill investigate further.

**Comment by Intecpsp** [comment] 2016-04-16 19:11
This looks like a previous issue:

[https://github.com/MichMich/MagicMirror/issues/159](url)

**Comment by Intecpsp** [comment] 2016-04-16 19:13
Clock and sunset still having issues:

![screen shot 2016-04-16 at 3 13 08 pm](https://cloud.githubusercontent.com/assets/1164012/14583102/cbbfee78-03e5-11e6-9666-9881caa8c273.png)

**Comment by MichMich** [comment] 2016-04-16 19:16
The problem is i can't debug since it doesn't happen here. Anyone able to debug it?

**Comment by MichMich** [comment] 2016-04-16 19:24
Could you test this fiddle to see if it gives the same issue: https://jsfiddle.net/qs0zq8n9

**Comment by roxasvalor** [comment] 2016-04-16 19:31
I'm running the snippet on the Pi without any issues.

Do you have any idea where I should look in the web inspector to find the source of the data?

Wish I could be more help but Javascript is pretty new to me.

**Comment by MichMich** [comment] 2016-04-16 19:34
Since the clock has the same issues. It isn't based on the data source.

**Comment by MichMich** [comment] 2016-04-16 19:37
Check this line:
https://github.com/MichMich/MagicMirror/blob/v2-beta/modules/default/clock/clock.js#L52

That's all it does. Maybe we could ask someone of the moment.js team to look at this issue ...

**Comment by Intecpsp** [comment] 2016-04-16 19:39
I wonder if moment.js can handle inline if statements? I modified the clock the take out the inline if, no issue so far. I didn't modify the sunrise/sunset inline if and it messed up.

**Comment by MichMich** [comment] 2016-04-16 19:40
That should not matter. The incline part just returns a string Moment uses.
Are you using 12 or 24 hour mode?

**Comment by Intecpsp** [comment] 2016-04-16 19:40
I'm using 12

**Comment by roxasvalor** [comment] 2016-04-16 19:41
I am using 12 as well. I modified the inline out too and so far no trouble.

**Comment by MichMich** [comment] 2016-04-16 19:43
Ok, please pull the latest version. This removed the inline statement.
(If this solves the issue, we discovered a javascript bug ... ;))

**Comment by Intecpsp** [comment] 2016-04-16 19:45
Just pulled, will let you know what I find.

**Comment by Intecpsp** [comment] 2016-04-16 19:47
Still have the issue:

![screen shot 2016-04-16 at 3 47 09 pm](https://cloud.githubusercontent.com/assets/1164012/14583261/82a3c4e4-03ea-11e6-85dc-b58d445bd7d1.png)

**Comment by MichMich** [comment] 2016-04-16 19:48
Could you try 24 hour mode. To see if that solves the issue? (The I know where to look ...)

**Comment by Intecpsp** [comment] 2016-04-16 19:58
Been running 24 hour format for 10 minutes with no issues. Looks like the issue is with the 12 hour format.

**Comment by MichMich** [comment] 2016-04-16 20:00
In that case, could you try the fiddle again: https://jsfiddle.net/qs0zq8n9/1/

**Comment by roxasvalor** [comment] 2016-04-16 20:15
The fiddle runs as expected but replicating that line in clock.js still fails.

**Comment by roxasvalor** [comment] 2016-04-16 20:23
This may be pretty obvious but the bug is also present when using "moment().format("h:mm a")".

**Comment by MichMich** [comment] 2016-04-16 20:23
Ok. I need to make a test setup for this. If I find a solution I'll let you know. 
Just to be sure; 24 hour mode gives no issues. Right?

**Comment by Intecpsp** [comment] 2016-04-16 20:24
Not that I've seen. 24 hour mode looks good.

**Comment by roxasvalor** [comment] 2016-04-16 20:24
No issues to report in 24 hour mode.

**Comment by jtyle6** [comment] 2016-04-17 13:40
Confirmed bug with 12 hour mode.

**Comment by MichMich** [comment] 2016-04-17 15:08
Its an overflow issue (the 2.2250... number isn't a random number, it's the minimum value javascript can handle.)

Just to be sure, it only happens on a Raspberry Pi, right?

**Comment by Intecpsp** [comment] 2016-04-17 15:13
I'm using a Raspberry Pi 3

**Comment by MichMich** [comment] 2016-04-18 17:13
I just pushed a fix which seems to solve the issue in my test setup. Could you give it a try?

**Comment by Intecpsp** [comment] 2016-04-18 23:00
Just pulled it, will let you know how it goes.

**Comment by MichMich** [comment] 2016-04-19 09:28
It did not happen anymore on my test setup. I close this issue for now, but if it happens again. Feel free to let me know in this issue.

**Comment by MichMich** [comment] 2016-05-10 11:43
This issue still messes up the calendar. I'm in contact with the moment.js team to look for a solution.

**Comment by MichMich** [comment] 2016-05-10 14:19
I just pushed an update with a modification to moment.js to find the cause of this issue. My Raspberry Pi seems to work ok now. Could you guys give it a try?

**Comment by MichMich** [comment] 2016-05-11 20:55
This problem seems to be solved. Let me know if it returns.

**Closed by MichMich** 2016-05-11 20:55 UTC
Labels: bug
