### ISSUE TITLE
Update newsfeed to accept and parse Atom feeds

### ISSUE THREAD

**Issue by falcofire** [MichMich/MagicMirror#242] opened 2016-04-24 23:40 UTC
This a request to update the stock newsFeed url to accept and parse Atom feed urls. The current newsFeed module does not parse any returned data from a reddit Atom url. Reddit [upgraded from RSS 2.0 to Atom 1.0](https://www.reddit.com/r/changelog/comments/428vdq/upcoming_reddit_change_switching_from_rss_20_to/) earlier this year. I suspect that is why the current implementation doesn't work. Having Reddit headlines in the feed seems like it might be a popular option.

Example url: (http://www.reddit.com/r/technology/.rss)

**Comment by MichMich** [comment] 2016-05-10 11:48
Duplicate of #231

**Closed by MichMich** 2016-05-10 11:48 UTC
Labels: enhancement
