### ISSUE TITLE
Weatherforecast module bug

### ISSUE THREAD

**Issue by sipuli93** [MichMich/MagicMirror#2047] opened 2020-06-17 09:13 UTC
**Platform**: Electron@6.1.7 on Raspberry Pi 4

**Node Version**: 10.20.1

**MagicMirror Version**: 2.11.0

**Description**: Using free openweathermap account and limiting forecast to under 7 days (6 days in my case) causes the last day of the forecast show only night data. 

![Screenshot from 2020-06-17 11-43-41](https://user-images.githubusercontent.com/66952910/84876510-f70f2c00-b08f-11ea-85f8-c6120086d05e.png)
Also nighttime weather icon is shown.

**Steps to Reproduce**: 
Use  "forecast" as endpoint for openweathermap api (free account)
Limit maxNumberOfDays to under 7

**Expected Results**: I expect to see Min and Max temperatures based on full day and to have day icon in forecast.

**Actual Results**: The last day of the forecast doesn't show data from whole day.

**Configuration**: 
var config = {
	address: "localhost", 
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],
	useHttps: false,
	httpsPrivateKey: "",
	httpsCertificate: "",
	language: "fi",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,

	modules: [
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left",
			config: {
				displaySeconds: false,
				timezone: "Europe/Helsinki"
			}
		},
		{
			module: "calendar",
			header: "Tapahtumat",
			position: "top_left",
			config: {
				maximumNumberOfDays: 90,
				calendars: [
					{
						symbol: "calendar-check",
						url: "https://rocketcal.s3.eu-central-1.amazonaws.com/launches.ics"
					}
				]
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Sääennuste",
			config: {
				location: "Alavus",
				tableClass: "large",
				maxNumberOfDays: 6,
				forecastEndpoint: "forecast",
				roundTemp: true,
				locationID: "661352",
				appid: "xxxxxxxxxxxxxxxx"
			}
		}
	]

};

**Additional Notes**: Moving forecast length check from lines 363-365 to line 351 seems to fix problem as we want prevent extra days from showing rather than stopping right after reaching the last day.

**Comment by hangorazvan** [comment] 2020-06-17 19:54
using the forecast endpoit give you the 3 by 3 hour forecast

We = 09h
Th = 12h
Fr = 15h
Sa = 18h
Su = 21h
mo = 00h

so last one is night

to display hours instead days you need to change line 343

`day = moment(forecast.dt_txt, "YYYY-MM-DD hh:mm:ss").format("ddd");`

with

`day = moment(forecast.dt_txt, "YYYY-MM-DD hh:mm:ss").format("HH");`

but if you want to use forecast for days you must use endpoint `forecast/daily`

**Comment by sipuli93** [comment] 2020-06-18 05:37
> using the forecast endpoit give you the 3 by 3 hour forecast
> 
> Your hour is 11:43 not yet 12.00 so
> 
> We = 09h
> Th = 12h
> Fr = 15h
> Sa = 18h
> Su = 21h
> mo = 00h
> 
> then last one is in the night

/forecast endpoint gives forecast for next 5 days in 3 hour steps ([Openweathermap](https://openweathermap.org/forecast5))
processWeather function iterates those 40 forecasts to get min and max temperatures for each day.

> hour = ... has no sens

The hour is used to get weather icon within the day. At line 374.

> but if you want to use forecast for days you must use endpoint `forecast/daily`

That would work as I wanted, but it's only for paid users.

**Comment by MichMich** [comment] 2020-07-04 19:56
This is not a bug, but a limitation based on open weather. Feel free to send a PR if you know a nice solution. Closing this issue for now.

**Closed by MichMich** 2020-07-04 19:56 UTC

**Comment by sthuber90** [comment] 2020-09-02 05:26
To warm this up and to checkin whether @sipuli93 has already found a solution, wouldn't it be possible to get for exampe one more day than you actually want to show?

**Comment by sipuli93** [comment] 2020-09-02 06:35
I ended up to use weather module with type forecast. It uses same endpoint and does same thing properly.
