### ISSUE TITLE
Calendar in the new MagicMirror²

### ISSUE THREAD

**Issue by powerscooter** [MichMich/MagicMirror#166] opened 2016-04-12 21:45 UTC
Hi,

i have tested your new MagicMirror²!
I have a question to the new calendar. The old calender have showed the events for example:
Birthday Party XYZ -> "in 4 hours" or "tomorrow at 23 o´clock"
Now the Calender show:
Birthday Party XYZ -> "Today"

Can you build in this function in the new Magic Mirror²?
Sorry for my bad english.

Regards,
Phil

**Comment by MichMich** [comment] 2016-04-13 07:17
If it's an all day event, it shows `Today`. Otherwise it should show the exact time. Could you confirm that by testing?

**Comment by MichMich** [comment] 2016-04-13 07:29
Duplicate of #162.

**Closed by MichMich** 2016-04-13 07:29 UTC
