### ISSUE TITLE
weatherforecast only showing 2 days, not the default 7.

### ISSUE THREAD

**Issue by hervidero** [MichMich/MagicMirror#2074] opened 2020-07-05 19:18 UTC
Default module weatherforecast started showing only a 2 day forecast recently instead of the default 7 day forecast.
I think openweathermap.org changed something, they now have 8 forecast moments per day.
As a result the mirror only shows 2 days of forecast with a default maxNumberOfDays: 7 in the config.js

If I change the weatherforecast.js so that &cnt=56 the mirror again shows a 7 day forecast. (as 8 moments * 7 days = 56)

**MagicMirror Version**: 2.12.0

**Comment by khassel** [comment] 2020-07-05 19:22
This is may a duplicate of https://github.com/MichMich/MagicMirror/issues/2065 which is already fixed on the `develop` branch.

**Comment by hervidero** [comment] 2020-07-05 19:30
After reading #2065, I can confirm it is the same issue.

**Comment by MichMich** [comment] 2020-07-05 20:07
Duplicate. Closing issue.

**Closed** 2020-07-05 20:08 UTC
