### ISSUE TITLE
Invalid svg clock faces

### ISSUE THREAD

**Issue by hangorazvan** [MichMich/MagicMirror#2072] opened 2020-07-05 07:09 UTC
All new 2.12.0 verison svg files in clock faces folder are invalid svg format, use the old ones.
I think replacing unsecure links with https ones make format invalid.

https://forum.magicmirror.builders/topic/13190/no-numbers-in-analog-watch-face

**Comment by MichMich** [comment] 2020-07-05 08:32
Does it prevent them from loading in electron? 
Feel free to send a PR. Although I think this is caused by prettier. So sending a PR might fail on Travis.

**Comment by MichMich** [comment] 2020-07-05 11:46
Fix merged into develop thanks to @rejas.

**Comment by hangorazvan** [comment] 2020-07-20 16:27
face-006.svg still not working

**Comment by MichMich** [comment] 2020-07-20 17:29
Should be fixed now. Thanks @rejas!

**Closed** 2020-07-20 17:43 UTC
