### ISSUE TITLE
Per Calendar fetchInterval

### ISSUE THREAD

**Issue by Klami** [MichMich/MagicMirror#1569] opened 2019-02-12 11:16 UTC
there are some calendars that allow only one fetch per day while others should update more frequently.

Solution add fetchInterval per Calendar:
```javascript
var calendarConfig = {
                maximumEntries: calendar.maximumEntries,
                maximumNumberOfDays: calendar.maximumNumberOfDays,
                fetchInterval: calendar.fetchInterval
            };

addCalendar: function (url, auth, calendarConfig) {
        this.sendSocketNotification("ADD_CALENDAR", {
            url: url,
            excludedEvents: calendarConfig.excludedEvents || this.config.excludedEvents,
            maximumEntries: calendarConfig.maximumEntries || this.config.maximumEntries,
            maximumNumberOfDays: calendarConfig.maximumNumberOfDays || this.config.maximumNumberOfDays,
            fetchInterval: calendarConfig.fetchInterval || this.config.fetchInterval,
            symbolClass: calendarConfig.symbolClass,
            titleClass: calendarConfig.titleClass,
            timeClass: calendarConfig.timeClass,
            auth: auth
        });
    },
```

**Comment by MichMich** [comment] 2019-02-14 12:52
Duplicate of #1359

**Closed by MichMich** 2019-02-14 12:52 UTC
