### ISSUE TITLE
Wont boot on pi2

### ISSUE THREAD

**Issue by pi-mad** [MichMich/MagicMirror#392] opened 2016-08-05 18:34 UTC
Installed using the automated way in command prompt and all installed fine, started it up and it said about the config so I went and don't that and now when I start it I get just a black screen with nothing on it, have I not done something right?

**Comment by MichMich** [comment] 2016-08-05 19:11
What version are you running. The master version has an issue with The 'en' language. If you run The develop branche it should be fixed.

**Comment by hazi2006** [comment] 2016-08-07 04:39
What do you mean by Develop Branch? I have the same problem on Pi3, when i run it, it appears as a black screen.

**Comment by MichMich** [comment] 2016-08-07 13:56
Duplicate of: https://github.com/MichMich/MagicMirror/issues/393

**Closed by MichMich** 2016-08-07 13:56 UTC
