### ISSUE TITLE
iCloud calendars not always working

### ISSUE THREAD

**Issue by paviro** [MichMich/MagicMirror#118] opened 2016-04-01 10:04 UTC
As you know my iCloud calendar does not work. I just created another test calendar which worked as expected but mine still does not.. Any way I can debug this?

**Comment by MichMich** [comment] 2016-04-01 10:13
First of: I'm working on the calendar integration now, in order to fix https://github.com/MichMich/MagicMirror/issues/115, so don't make any changes to the calendar module (else I won't be able to merge the pull request.)

Your issue is probably caused by not using the correct url, are you using a public url?

**Comment by paviro** [comment] 2016-04-01 10:24
Yes, I am using the correct URL, tried it with another calendar in exactly the same way and it worked there.

**Comment by MichMich** [comment] 2016-04-01 10:25
Can you share the non working URL?

**Comment by paviro** [comment] 2016-04-01 10:26
Well it's my private calendar, I could send it to you via e-mail?

**Comment by MichMich** [comment] 2016-04-01 10:27
That's ok: michael [at] xonaymedia.nl

**Comment by MichMich** [comment] 2016-04-01 11:18
@paviro This should be fixed now. Could you give it a try and close this issue when it's fixed? https://github.com/MichMich/MagicMirror/commit/46312cb44c08f1b1805a141d52af6863b0f5f098

**Closed** 2016-04-01 12:24 UTC

**Comment by paviro** [comment] 2016-04-01 12:25
Sorry is fixed wasn't fast enough.
