### ISSUE TITLE
config.js clock module format

### ISSUE THREAD

**Issue by antidefran** [MichMich/MagicMirror#171] opened 2016-04-13 20:45 UTC
Haven't seen any other posts for this issue:

has anyone had an issue when changing config.js timeformat to 12 instead of 24? when I write the change and restart magic mirror, it displays the time in the correct format for about 2 minutes and 10 seconds, then the time format "explodes" into a large decimal number that throws the whole magic mirror off. 

any suggestions? 
![clock module error](https://cloud.githubusercontent.com/assets/5819539/14508745/ffb9c330-0196-11e6-8bd6-d593f9b665ca.jpg)

**Comment by MichMich** [comment] 2016-04-13 21:13
Duplicate of #159

**Closed by MichMich** 2016-04-13 21:13 UTC
