### ISSUE TITLE
Analog clock not scaling correct the faces

### ISSUE THREAD

**Issue by olovskos** [MichMich/MagicMirror#682] opened 2017-02-03 13:29 UTC
I don't know why and I`m not interested in digging deeper into but if you use the analog clock, you cannot resize it. It just shows multiple of the face selected

**Comment by morozgrafix** [comment] 2017-02-03 16:54
@olovakos can you please provide relevant snippets of your `config.js`? Thanks

**Comment by olovskos** [comment] 2017-02-03 20:22
Yes of course I can :)       

{
        module: "clock",
        position: "top_left", 
        config: {
            displayType: 'analog',
            analogSize: '300px',
            analogFace: 'face-002'
        }
}

**Comment by morozgrafix** [comment] 2017-02-03 21:33
I wasn't able to reproduce it in Chrome or Electron on my mac on both latest version of master and develop branches. I don't have access to RasPi until later to test it out. Here is what I get when I use settings that you've provided:

![image](https://cloud.githubusercontent.com/assets/1007608/22609256/5526d08a-ea15-11e6-8301-e586d29d1ddc.png)

**Comment by olovskos** [comment] 2017-02-03 23:00
This is how it looks like
![untitled](https://cloud.githubusercontent.com/assets/7429904/22611742/9cf7a9fa-ea6c-11e6-9c9b-1c89396e9282.png)

BUT
I changed the size of the fonts by changeing the custom.css regarding this link  
[https://forum.magicmirror.builders/topic/74/adjust-modules-size-to-match-each-other-weather-calendar/2](url)

And now it looks fine but this can't be the solution of the problem. 

I`m using a RPI 3 with the newest raspbian.

**Comment by morozgrafix** [comment] 2017-02-03 23:58
Seems that few people on the forum are [having issues with it](https://forum.magicmirror.builders/search?term=analog%20clock&in=titlesposts) scaling correctly

**Comment by roramirez** [comment] 2017-02-04 02:54
Maybe @KirAsh4 can help with this. He introduced the feature for analog clock ;)

**Comment by MichMich** [comment] 2017-02-07 11:24
@olovskos what branch/version are you running? I used a fix for this a while ago.

**Comment by KirAsh4** [comment] 2017-02-09 05:52
Since released, I have not doing any scaling tests with subsequent updates to electron, but it appears to be broken now. I'll have to go dig into the CSS a bit and figure out why it's failing.

**Comment by MichMich** [comment] 2017-02-09 07:43
@KirAsh4, are you testing the develop branch, or the master branch?

**Comment by KirAsh4** [comment] 2017-02-09 07:55
I like living on the edge.
develop branch.

**Comment by MichMich** [comment] 2017-02-09 12:29
Then it should be solved ... it isn't?

**Comment by MichMich** [comment] 2017-04-05 18:21
Closing due to inactivity.

**Closed by MichMich** 2017-04-05 18:21 UTC

**Comment by KirAsh4** [comment] 2017-04-05 19:17
I don't think this was an actual issue after it was fixed (by you). I haven't had any problems with it.

**Comment by MichMich** [comment] 2017-04-05 19:29
Good to hear! Thanks.
