### ISSUE TITLE
UpdateNotification fetch errors if github is unavailable

### ISSUE THREAD

**Issue by erdoukki** [MichMich/MagicMirror#1555] opened 2019-01-28 15:24 UTC
UpdateNotification module made a lot of fetch error (DNS problems may locally be in trouble also)

Disabling UpdateNotiifcations may fix the issue.

---
fatal: unable to access 'https://github.com/MichMich/MagicMirror/': Could not resolve host: github.com

fatal: unable to access 'https://github.com/spectroman/mmm-moon-phases.git/': Could not resolve host: github.com

fatal: unable to access 'https://github.com/dmcinnes/MMM-forecast-io.git/': Could not resolve host: github.com

fatal: unable to access 'https://github.com/dmcinnes/MMM-forecast-io.git/': Could not resolve host: github.com

fatal: unable to access 'https://github.com/MichMich/MagicMirror/': Could not resolve host: github.com

fatal: unable to access 'https://github.com/spectroman/mmm-moon-phases.git/': Could not resolve host: github.com

fatal: unable to access 'https://github.com/MichMich/MagicMirror/': Could not resolve host: github.com

**Comment by JohnB7777** [comment] 2019-01-29 16:46
Hello,

I have the same error !
At the beginning, I thought it was because one of my module wasn't update but no.
And I have already my internet connection.
So... I don't understand.

**Comment by ezar** [comment] 2019-03-24 06:26
Same here

**Comment by MichMich** [comment] 2019-05-21 09:23
Well ... yes. If there is o connection, there is an error. So it is reported. The number of errors could be decreased but other than that, it's expected behaviour. Feel free to send a PR to solve this.

Closing this issue for now.

**Closed by MichMich** 2019-05-21 09:23 UTC

**Comment by theforceofhabit** [comment] 2021-06-04 11:51
anyone found a solution yet?
