### ISSUE TITLE
Clock faces not showing after Upgrading to MM 2.12 

### ISSUE THREAD

**Issue by hriday-khurana** [MichMich/MagicMirror#2096] opened 2020-07-20 17:29 UTC
My analog clock faces are not visible anymore after upgrading to MagicMirror 2.12, not sure if anyone else experienced this or not?

Can you please check if it works for others?
i have face-004 configured in config file but i dont see it on MagicMirror.

![image](https://user-images.githubusercontent.com/60769531/87967590-0ae1ef80-ca8d-11ea-97cd-6103992ac466.png)

**Comment by MichMich** [comment] 2020-07-20 17:43
Duplicate of: https://github.com/MichMich/MagicMirror/issues/2072

**Closed by MichMich** 2020-07-20 17:43 UTC
